# Generated by Django 3.1.7 on 2021-02-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
