# Generated by Django 3.1.7 on 2021-02-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_owner_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='vehicle_location',
            new_name='Address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='Accelerometer',
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(default='bot', max_length=50),
        ),
    ]
