# Generated by Django 3.1.7 on 2021-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210301_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='id',
        ),
        migrations.AlterField(
            model_name='owner',
            name='adhar',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
